# Generated by Django 6.0.1 on 2026-09-09 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bee", "bee"),
                            ("bison", "bison"),
                            ("camel", "camel"),
                            ("cat", "cat"),
                            ("chameleon", "chameleon"),
                            ("crab", "crab"),
                            ("deer", "deer"),
                            ("dog", "dog"),
                            ("dolphin", "dolphin"),
                            ("duck", "duck"),
                            ("elephant", "elephant"),
                            ("fish", "fish"),
                            ("flamingo", "flamingo"),
                            ("frog", "frog"),
                            ("giraffe", "giraffe"),
                            ("hedgehog", "hedgehog"),
                            ("hen", "hen"),
                            ("hermit-crab", "hermit-crab"),
                            ("hippopotamus", "hippopotamus"),
                            ("horse", "horse"),
                            ("jellyfish", "jellyfish"),
                            ("kangaroo", "kangaroo"),
                            ("kiwi", "kiwi"),
                            ("koala", "koala"),
                            ("lion", "lion"),
                            ("llama", "llama"),
                            ("lobster", "lobster"),
                            ("meerkat", "meerkat"),
                            ("monkey", "monkey"),
                            ("octopus", "octopus"),
                            ("ostrich", "ostrich"),
                            ("owl", "owl"),
                            ("panda-bear", "panda-bear"),
                            ("parrot", "parrot"),
                            ("penguin", "penguin"),
                            ("pig", "pig"),
                            ("rabbit", "rabbit"),
                            ("seahorse", "seahorse"),
                            ("seal", "seal"),
                            ("shark", "shark"),
                            ("sheep", "sheep"),
                            ("snail", "snail"),
                            ("snake", "snake"),
                            ("squid", "squid"),
                            ("squirrel", "squirrel"),
                            ("swan", "swan"),
                            ("toucan", "toucan"),
                            ("turtle", "turtle"),
                            ("walrus", "walrus"),
                            ("whale", "whale"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
