# Generated by Django 6.0.1 on 2026-09-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="govex_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
