# Generated by Django 6.0.8 on 2026-09-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_govex_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
