# Generated by Django 6.0.8 on 2026-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsent",
            name="cookies",
            field=models.BooleanField(default=False),
        ),
    ]
