services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: buechijonas/wintersehn-backend:latest

    restart: unless-stopped

    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: "false"
      DJANGO_ALLOWED_HOSTS: ${DOMAIN},backend
      DJANGO_CSRF_TRUSTED_ORIGINS: https://${DOMAIN}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: buechijonas/wintersehn-proxy:latest

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      DOMAIN: ${DOMAIN}
      ACME_EMAIL: ${ACME_EMAIL}

    volumes:
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - backend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
