# Generated by Django 6.0.1 on 2026-09-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_seed_legal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitecontent",
            options={
                "permissions": [
                    ("view_ethos", "Can view Ethos"),
                    ("view_cv", "Can view Lebenslauf"),
                    ("view_media", "Can view Medien (Arbeit)"),
                    ("view_admin", "Can view the admin panel"),
                    ("manage_permissions", "Can manage role permissions"),
                    ("manage_roles", "Can add, rename and delete roles"),
                ]
            },
        ),
    ]
